### ISSUE TITLE
Love the project - Setup Issue

### ISSUE THREAD

**Issue by Shaburu** [Mayuresh1611/Paper-Piano#2] opened 2024-03-10 10:13 UTC
![image](https://github.com/Mayuresh1611/Paper-Piano/assets/67481819/b2e17d20-bace-4735-9f2b-1c18793e7395)

**Comment by Mayuresh1611** [comment] 2024-03-10 11:59
Can you provide more information like at what point it occurred, which steps lead it up to this

**Comment by Shaburu** [comment] 2024-03-10 14:03
i followed the pip i -requirements.txt then run the .py file and i got the following error

**Comment by Mayuresh1611** [comment] 2024-03-11 14:00
Fixed the error,
It was due to the model getting called before it was trained in the model.py during module import.

**Comment by ramyareye** [comment] 2024-03-12 04:21
@Mayuresh1611 I'm having same problem yet, 

after running `python3 run.php` I get this 
`FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'models/touch_detection_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

**Comment by Mayuresh1611** [comment] 2024-03-12 06:29
now it should work.
I didn't knew empty repos are not committed. People who cloned this project before mush have had really hard times.

**Comment by Mayuresh1611** [comment] 2024-03-14 03:10
Umm that is unexpected behavior, did the mesh formed on paper when you pressed q?

**Closed** 2024-03-15 06:52 UTC
